#      __            __          
#     / /  ___ ____ / /  ________
#  _ / _ \/ _ `(_-</ _ \/ __/ __/
# (_)_.__/\_,_/___/_//_/_/  \__/ 


# Do NOT edit this file!
# It uses auto-updates by default and will be eventually overridden
# To disable auto-updates set below provided constant to false

readonly AURORA_AUTO_UPDATES=true                   # Enable automatic updates
readonly AURORA_LOGIN=true                          # Enable compositor selection screen 
readonly AURORA_TMUX=true                           # Enable automatic tmux sessions
readonly AURORA_SERVICE=true                        # Enable services like low battery warning (needs AURORA_LOGIN to be enabled)

readonly AURORA_AUTO_UPDATES_INTERVAL=48            # Interval used for automatic updates (in hours)
readonly AURORA_AUTO_UPDATE_URL="https://raw.githubusercontent.com/hlasitahudbabezzvuku/aurora/refs/heads/development/bashrc"

readonly AURORA_CMD_REBOOT="systemctl reboot"       # Command used for rebooting the system
readonly AURORA_CMD_POWEROFF="systemctl poweroff"   # Command used for powering off the system
readonly AURORA_CMD_HIBERNATE="systemctl hibernate" # Command used for hibernating the system

readonly AURORA_SERVICE_INTERVAL=120                # Interval user for running watchdogs (in seconds)
readonly AURORA_SERVICE_BAT_WARNING=20              # Battery level treshold for warning notification
readonly AURORA_SERVICE_BAT_CRITICAL=10             # Battery level treshold for critical notification
readonly AURORA_SERVICE_BAT_HIBERNATE=5             # Battery level treshold for hibernaating the system


##################
### Enviroment ###
##################

if ! [[ "${PATH}" =~ "${HOME}/.local/bin" ]]; then
    PATH="${HOME}/.local/bin:${PATH}"
fi

if ! [[ "${PATH}" =~ "${HOME}/bin" ]]; then
    PATH="${HOME}/bin:${PATH}"
fi

export PATH


#####################
### Runtime Check ###
#####################

if [[ ! "${BASH_VERSINFO[0]}" -ge 5 ]]; then
    printf "[ERROR]: This script need BASH version 5 at least. Your version is %i\n" "${BASH_VERSINFO[0]}" 1>&2
    exec bash --norc --noprofile
fi

declare -a software_required=(
    "bash"
    "kill" # util-linux
    "date" # coreutils
    "tty"  # coreutils
    "tput" # ncurses
)

# opts: tmux, notify-send, curl

for i in "${software_required[@]}"; do
    if ! type "${i}" &> /dev/null; then
        printf "[ERROR]: Could not find \"%s\"\n" "${i}" 1>&2
        exec bash --norc --noprofile
    fi
done

unset software_required


###############
### Updates ###
###############

if "${AURORA_AUTO_UPDATES}" && [[ -z ${_aurora_first_login+x} ]] && type curl &> /dev/null && [[ $( date +%s --reference "${HOME}"/.nevim.txt ) -lt $(( $( date +%s ) - ( AURORA_AUTO_UPDATES_INTERVAL * 60 * 60 ) )) ]]; then
    ( output=$( curl --silent --fail "${AURORA_AUTO_UPDATE_URL}" ) && bash -n <<< "${output}" &> /dev/null && printf "%s" "${output}" > "${HOME}"/.bashrc & )
fi


#############
### Login ###
#############

if ${AURORA_LOGIN} && [[ $( tty ) == /dev/tty* ]] && [[ -z ${_aurora_first_login+x} ]]; then
    export _aurora_first_login=false

    declare -A software_all=(
        ["Cage"]="cage"
        ["DWL"]="dwl"
        ["Steamdeck Mode"]="gamescope -e -- steam -tenfoot"
        ["Hyprland"]="Hyprland"
        ["KWin"]="kwin_wayland"
        ["LabWC"]="labwc"
        ["Miracle"]="miracle-wm"
        ["niri"]="niri --session"
        ["Qtile"]="qtile start -b wayland"
        ["River"]="river"
        ["Sway"]="sway --unsupported-gpu"
        ["SwayFX"]="swayfx --unsupported-gpu"
        ["Wayfire"]="wayfire"
        ["Weston"]="weston"
    )

    declare -a software_avalible

    for i in "${!software_all[@]}"; do
        if type "${software_all[${i}]%% *}" &> /dev/null; then
            software_avalible+=( "${i}" )
        fi
    done

    height=${#software_avalible[@]} 

    start_col=$(( $( tput cols ) / 2 - 15 ))
    start_row=$(( $( tput lines ) / 2 - ( height + 12 ) / 2 ))

    while true; do
        tput reset

        tput cup $start_row ${start_col}
        printf "┌────── START SESSION ──────┐"

        for i in "${!software_avalible[@]}"; do
            tput cup $(( start_row + i + 2 )) ${start_col}
            printf "   %i   %s" $(( i + 1 )) "${software_avalible[${i}]}"
        done

        tput cup $(( start_row + height + 3 )) ${start_col}
        printf "└───────────────────────────┘"

        tput cup $(( start_row + height + 4 )) ${start_col} 
        printf "┌────── OTHER ACTIONS ──────┐"

        tput cup $(( start_row + height + 6 )) ${start_col} && printf "   %c   %s" "q" "Exit"
        tput cup $(( start_row + height + 7 )) ${start_col} && printf "   %c   %s" "s" "Shell (Full)"
        tput cup $(( start_row + height + 8 )) ${start_col} && printf "   %c   %s" "a" "Shell (Minimal)"
        tput cup $(( start_row + height + 9 )) ${start_col} && printf "   %c   %s" "r" "Reboot"
        tput cup $(( start_row + height + 10 )) ${start_col} && printf "   %c   %s" "p" "Poweroff"

        tput cup $(( start_row + height + 12 )) ${start_col}
        printf "└───────────────────────────┘"

        tput cup $(( start_row + height + 14 )) ${start_col}
        read -p " > " -n 1 -r input

        if [[ ${input} == "q" ]] || [[ ${input} == "e" ]]; then
            break
        elif [[ ${input} == "s" ]]; then
            tput reset
            bash
        elif [[ ${input} == "a" ]]; then
            tput reset
            bash --norc --noprofile
        elif [[ ${input} == "r" ]]; then
            ${AURORA_CMD_REBOOT}
        elif [[ ${input} == "p" ]]; then
            ${AURORA_CMD_POWEROFF}
        elif [[ ${input} -gt 0 ]] && [[ ${input} -le ${height} ]]; then
            tput reset

            ${software_all[${software_avalible[$(( input - 1 ))]}]} & pid_cmp=$!

            while ${AURORA_SERVICE} && type notify-send; do
                sleep ${AURORA_SERVICE_INTERVAL}

                capacity=$( < /sys/class/power_supply/BAT?/capacity )
                status=$( < /sys/class/power_supply/BAT?/status )
                if [[ ${status} != "Charging" ]] && [[ ${capacity} -le ${AURORA_SERVICE_BAT_HIBERNATE} ]]; then
                    notify-send --app-name=aurora --urgency=critical "Critical Battery State" "System will hibernate in 20 seconds."
                    sleep 20 && ${AURORA_CMD_HIBERNATE}
                elif [[ ${status} != "Charging" ]] && [[ ${capacity} -le ${AURORA_SERVICE_BAT_CRITICAL} ]]; then
                    notify-send --app-name=aurora --urgency=critical "Battery Capacity: ${capacity}" "Below critical operating level."
                elif [[ ${status} != "Charging" ]] && [[ ${capacity} -le ${AURORA_SERVICE_BAT_WARNING} ]]; then
                    notify-send --app-name=aurora --urgency=normal "Battery Capacity: ${capacity}" "Approaching low power threshold."
                fi

            done & pid_wdg=$!

            wait ${pid_cmp} && if ${AURORA_SERVICE}; then kill ${pid_wdg}; fi
        fi
    done
    exit
fi


####################
### Tmux Session ###
####################

if "${AURORA_TMUX}" && type tmux &> /dev/null && [[ -z "${TMUX+x}" ]]; then
    mapfile -t sessions < <( tmux list-sessions )

    for i in "${sessions[@]/:*/}"; do
        clients=$( tmux list-clients -t "${i}" )

        if [[ ! "${clients}" ]]; then
            exec tmux attach-session -t "${i}"
        fi
    done

    for (( i = 0; i < 128; i++ )); do
        if [[ ! "${sessions[*]/:*/}" =~ "${i}" ]]; then
            exec tmux new-session -s "${i}"
        fi
    done

    if type notify-send; then notify-send --app-name=aurora --urgency=critical "ERROR" "Could not find any free tmux session."; fi
    exec bash --norc --noprofile
fi


################
### Sourcing ###
################

if [[ -f /etc/bashrc ]]; then
    source /etc/bashrc
fi

if [ -d "${HOME}"/.config/bash ]; then
    for i in "${HOME}"/.config/bash/*.sh; do
        if [ -f "${i}" ]; then
            source "${i}"
        fi
    done
fi


